repos:

-   repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    - id: black

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-ast
  - id: trailing-whitespace
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: '.bumpversion.cfg'
