name: CI

on:
  push:
    branches:
      - master
    tags:
      - v**
  pull_request:

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [ 3.8, 3.9. 3.10, 3.11 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - run: pip install --upgrade pip
      - run: pip install poetry
      - run: poetry config --local virtualenvs.in-project true
      - run: poetry install
      - run: poetry run pre-commit run -a
      - run: cp .github-ci.env .env
      - run: poetry run pytest
      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./coverage.xml

  publish:
    if: startsWith(github.event.ref, 'refs/tags')
    name: publish
    needs: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - run: pip install --upgrade pip
      - run: pip install poetry
      - run: poetry build
      - uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}

  upload-to-codecov:
    needs:
      - pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: coverage-report
      - uses: codecov/codecov-action@v1
