name: CI

on:
  push:
    branches:
      - master
    tags:
      - v**
  pull_request:

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [ "3.8", "3.9", "3.10", "3.11" ]
        requests: [ "2.26", "2.27", "2.28", "2.29" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - run: pip install --upgrade pip
      - run: pip install poetry
      - run: poetry config --local virtualenvs.in-project true
      - run: poetry install
      - run: poetry add requests@~${{ matrix.requests }}
      - run: cp .github-ci.env .env
      - run: poetry run pytest
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report-python-${{ matrix.python }}-requests-${{ matrix.requests }}
          path: ./coverage.xml
          overwrite: true

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - uses: pre-commit/action@v3.0.0

  publish:
    if: startsWith(github.event.ref, 'refs/tags')
    name: publish
    needs: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
          architecture: x64
      - run: pip install --upgrade pip
      - run: pip install poetry
      - run: poetry build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.pypi_password }}

  upload-to-codecov:
    needs:
      - pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: coverage-report-*
          path: coverage-reports
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage-reports
